version: '3'

volumes:
  pg_data_production_t:
  static_volume_t:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production_t:/var/lib/postgresql/data
  backend:
    image: artist9/taski_backend
    env_file: .env
    volumes:
      - static_volume_t:/backend_static
  frontend:
    image: artist9/taski_frontend  
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_t:/frontend_static
  gateway:
    image: artist9/taski_gateway
    env_file: .env
    volumes:
      - static_volume_t:/staticfiles/
    ports:
      - 8000:80